version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean install
      - mvn surefire-report:report
  post_build:
    commands:
      - echo Build completed successfully
artifacts :
  files:
    - target/TechnicalBootcamp.jar
  discard-paths: yes

reports:
  SurefireReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: 'target/surefire-reports' # Location of the reports