version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean install
      - mvn test
  post_build:
    commands:
      - echo Build completed successfully
artifacts :
  files:
    - target/TechnicalBootcamp.jar
  discard-paths: yes

reports:
  arn:aws:codebuild:us-west-2:016604952143:report-group/TechnicalBootCampReport:
    file:
      - '**/*'
    base-directory: 'target/cucumber-reports'