version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-firefox:4.1.2-20220217
      - mvn clean install
  post_build:
    commands:
      - echo Build completed successfully
artifacts :
  files:
    - target/TechnicalBootcamp.jar
  discard-paths: yes

reports:
  SurefireReports:
    files:
      - '**/*'
    base-directory: 'target/surefire-reports' # Location of the reports

  jacoco-report:
    files:
      - 'target/my-reports/jacoco.xml'
    file-format: 'JACOCOXML'


