version: 0.2

phases:
  build:
    commands:
      - mvn clean test
      - mvn jacoco:report
      - mvn surefire-report:report

  post_build:
    commands:
      - echo Build completed successfully
artifacts :
  files:
    - target/TechnicalBootcamp.jar
  discard-paths: yes

reports:
  SurefireReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: 'target/surefire-reports' # Location of the reports


  jacoco-report:
    files:
      - 'target/site/jacoco/jacoco.xml'
    file-format: 'JACOCOXML'
    base-directory: 'target/site/jacoco' # Location of the reports

