version: 0.2

phases:
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - echo Build completed successfully
artifacts :
  files:
    - target/TechnicalBootcamp.jar
  discard-paths: yes

reports:
  SurefireReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: 'target/surefire-reports' # Location of the reports

    jacoco-report:
      files:
        - 'target/my-reports/jacoco.xml'
      file-format: 'JACOCOXML'


